// Original buyer guidance. Manufacturer figures are dated references, not dealer quotes.
export const guideCards = `<div class="guide-grid"><article><span class="kicker">SUV SHORTLIST</span><h3><a href="/comparisons/corolla-cross-vs-rav4/">Corolla Cross vs RAV4: compare the right versions</a></h3><p>Canadian and U.S. starting prices, drivetrain differences and a practical showroom plan.</p></article><article><span class="kicker">BEFORE THE QUOTE</span><h3><a href="/guides/compare-car-quotes/">How to compare two car quotes</a></h3><p>Separate the vehicle, fees and financing so a monthly payment does not hide the decision.</p></article><article><span class="kicker">DAILY USE</span><h3><a href="/guides/cabin-tech-test-drive/">Test the cabin tech you will actually use</a></h3><p>A repeatable phone, parking and passenger check for your next test drive.</p></article></div>`;

export function searchContentPages(pageIntro) {
  const written = '2026-10-02';
  const wrap = (intro, content) => intro + `<div class="shell prose-page"><article class="prose">${content}<div class="share-tools"><button type="button" class="button secondary" data-share hidden>Share this guide</button><span data-share-status role="status"></span></div></article><aside class="policy-aside"><h2>Your next step</h2><a href="/tools/test-drive-checklist/">Take the test-drive checklist</a><a href="/tools/fuel-cost-calculator/">Compare annual fuel costs</a><a href="/long-videos/">Watch the full reviews</a><a href="/follow/">Follow new coverage</a></aside></div>`;
  return [
    {route:'/comparisons/corolla-cross-vs-rav4/', title:'2026 Corolla Cross vs RAV4: Canadian & U.S. buyer comparison', description:'Compare dated Toyota starting prices, Canadian and U.S. drivetrain choices, and the questions to answer before choosing a 2026 Corolla Cross or RAV4.', written,
      body:wrap(pageIntro('2026 / SUV BUYER GUIDE','Corolla Cross or RAV4? Start with the version.','The starting price only helps when the market, drivetrain and trim are clear.',[['Comparisons','/comparisons/'],['Corolla Cross vs RAV4',null]]),`
        <p class="updated">By <a href="/about/">Rishi · AutoTech Review</a> · Sources checked October 2, 2026</p>
        <p>Put both SUVs on your shortlist if you are weighing a Toyota daily driver. First decide whether you are comparing gas with hybrid, front-wheel drive with all-wheel drive, or the equipment in two specific trims. The cheapest Corolla Cross and cheapest RAV4 do not represent the same powertrain.</p>
        <p><a class="button" href="/watch/2026-corolla-cross-vs-rav4-canada/">Watch Rishi’s comparison</a> <a class="text-link" href="/videos/2026-corolla-cross-vs-rav4-canada/">Open the video companion</a></p>
        <h2 id="pricing">Dated starting prices: Canada and the U.S.</h2>
        <p>These are manufacturer-published 2026 starting MSRPs in each local currency. They are a reference for the named versions, not current offers. Confirm the latest configuration and a written quote with your retailer.</p>
        <div class="table-scroll" tabindex="0" role="region" aria-label="Canadian and U.S. Toyota starting prices"><table class="buyer-table"><caption>2026 entry versions in Toyota’s published price announcements</caption><thead><tr><th scope="col">Market</th><th scope="col">Version</th><th scope="col">Starting MSRP</th></tr></thead><tbody>
        <tr><td>Canada · CAD</td><td>Corolla Cross L FWD · gas</td><td>$28,580</td></tr><tr><td>Canada · CAD</td><td>Corolla Cross Hybrid SE AWD</td><td>$35,810</td></tr><tr><td>Canada · CAD</td><td>RAV4 LE AWD · hybrid</td><td>$37,500</td></tr>
        <tr><td>U.S. · USD</td><td>Corolla Cross L FWD · gas</td><td>$24,635</td></tr><tr><td>U.S. · USD</td><td>Corolla Cross Hybrid S AWD</td><td>$28,995</td></tr><tr><td>U.S. · USD</td><td>RAV4 LE FWD · hybrid</td><td>$31,900</td></tr></tbody></table></div>
        <p>Canada’s quoted MSRP excludes freight/PDI and other charges. Toyota Canada lists an estimated vehicle price separately, with specified fees, before tax, licensing, insurance and registration. U.S. MSRP excludes dealer processing and handling; tax, title and other applicable charges also affect the final quote. CAD and USD figures are not directly interchangeable.</p>
        <h2 id="drivetrain">The market changes the comparison</h2>
        <p>Toyota’s Canadian 2026 RAV4 announcement specifies standard AWD. Its U.S. announcement includes a front-wheel-drive hybrid entry model. The Corolla Cross offers gas and hybrid choices; the hybrid uses AWD. Compare a Canadian Corolla Cross Hybrid SE AWD with a Canadian RAV4 LE AWD before treating their price gap as a like-for-like hybrid comparison.</p>
        <h2 id="shortlist">Make the showroom visit answer three questions</h2>
        <ol><li><strong>Does your real cargo fit?</strong> Take your stroller, sports bag or luggage. Check the loading opening, floor height and remaining passenger space with the front seat set for your driver.</li><li><strong>Which features matter every day?</strong> Write down your must-haves, then confirm each one on the exact trim and market. Test the phone connection, reversing view and climate controls yourself.</li><li><strong>What is the total cost for your use?</strong> Ask for itemized quotes for both vehicles. Use the <a href="/tools/fuel-cost-calculator/">fuel-cost calculator</a> with official ratings for the exact versions and your own annual distance. Keep insurance, service and financing separate from fuel.</li></ol>
        <h2 id="questions">Common buying questions</h2>
        <details class="buyer-faq"><summary>Should I pick the Corolla Cross because its starting price is lower?</summary><p>Use that price to decide whether to investigate it. Then compare the version with your required drivetrain and equipment. The entry gas FWD model and an AWD hybrid answer different requirements.</p></details>
        <details class="buyer-faq"><summary>Can I use a U.S. review to shop in Canada?</summary><p>Use it to understand the vehicle, then verify the Canadian trim, features, warranty and price. The RAV4’s entry drivetrain is one concrete difference in this comparison.</p></details>
        <details class="buyer-faq"><summary>Where can I check the rear seat before visiting a retailer?</summary><p>Start with the <a href="/vehicles/2026-toyota-corolla-cross-hybrid/">Corolla Cross video collection</a> and its back-seat Short. Then test your own seating position during the visit.</p></details>
        <h2 id="sources">Manufacturer sources</h2><ul class="source-list">
        <li><a href="https://media.toyota.ca/en/releases/2025/what-s-new--the-2026-toyota-corolla-cross.html">Toyota Canada: 2026 Corolla Cross</a> · August 12, 2025</li>
        <li><a href="https://media.toyota.ca/en/releases/2026/the-canadian-built-rav4-is-all-new-for-2026--and-offered-at-sugg.html">Toyota Canada: 2026 RAV4 prices</a> · January 2026</li>
        <li><a href="https://pressroom.toyota.com/assembled-in-america-and-arriving-now-2026-toyota-corolla-cross/">Toyota USA: 2026 Corolla Cross prices</a> · September 24, 2025</li>
        <li><a href="https://pressroom.toyota.com/the-next-adventure-begins-2026-rav4-arrives-this-winter/">Toyota USA: 2026 RAV4</a> · updated May 8, 2026</li></ul>
        <p class="market-note">This guide combines published manufacturer facts with a practical comparison checklist. It adds no measured fuel economy, winter test result or driving verdict beyond the video. <a href="/transparency/">Editorial standards</a> · <a href="mailto:autotechreview51@gmail.com?subject=Comparison%20guide%20correction">Suggest a correction</a></p>`)
    },
    {route:'/guides/compare-car-quotes/',title:'How to compare car quotes in Canada and the U.S.',description:'A practical checklist for comparing vehicle prices, fees, finance terms and dealer add-ons without losing sight of the total cost.',written,
      body:wrap(pageIntro('BUYING GUIDE / YOUR NEXT QUOTE','Two quotes. One clear comparison.','Match the vehicle and separate the numbers before deciding which offer fits.',[['Buying guides','/guides/'],['Compare car quotes',null]]),`
        <p class="updated">By <a href="/about/">Rishi · AutoTech Review</a> · October 2, 2026</p>
        <p>A lower monthly payment can come from a longer loan, a larger down payment or a different vehicle. Put two written offers side by side before choosing. Use the same currency and market, and leave personal information out of any notes or links you share.</p>
        <h2>Start with the exact car</h2><p>Record the model year, trim, drivetrain, factory options and whether the vehicle is new, used or a demonstrator. Ask for the VIN or stock number. For a used vehicle, compare mileage, condition, service history and the warranty actually included.</p>
        <h2>Ask for the vehicle price and an itemized total</h2><p>Request the selling price before financing, then a list of freight or destination charges, dealer fees, taxes, registration and add-ons. Ask which items are optional, whether they can be removed and how the total changes. Do not assume the same fee rules apply in every province or state.</p>
        <div class="table-scroll" tabindex="0" role="region" aria-label="Car quote comparison checklist"><table class="buyer-table"><caption>Fields to request in both written offers</caption><thead><tr><th scope="col">Field</th><th scope="col">What to match or clarify</th></tr></thead><tbody><tr><th scope="row">Vehicle</th><td>Year, trim, drivetrain, options, stock number and condition</td></tr><tr><th scope="row">Price and fees</th><td>Selling price, mandatory charges, optional products and tax</td></tr><tr><th scope="row">Financing</th><td>APR, term, amount financed, payment frequency and total repayment</td></tr><tr><th scope="row">Upfront money</th><td>Down payment, deposit terms and trade-in shown separately</td></tr><tr><th scope="row">Timing</th><td>Offer expiry, delivery date and any availability conditions</td></tr></tbody></table></div>
        <h2>Compare finance terms separately</h2><p>Ask for the annual percentage rate, length of the loan, number and frequency of payments, amount financed and total amount payable. Request the terms without a trade-in first, then add the trade-in so you can see its effect. A longer repayment period can reduce each payment while changing the total you repay.</p>
        <p>For a lease, also compare the distance allowance, upfront amount, term, end-of-lease purchase option and the stated wear or excess-distance charges. Confirm whether advertised payments include tax. Get any deposit refund conditions in writing before paying.</p>
        <h2>Add the costs of your own driving</h2><p>Get insurance quotes for the exact vehicles and ask about the service schedule. Compare fuel using your actual annual distance and local fuel price in the <a href="/tools/fuel-cost-calculator/">annual fuel-cost calculator</a>. It is a fuel estimate; it does not calculate financing, taxes, insurance or total ownership cost.</p>
        <h2>Leave with a decision you can explain</h2><p>Write one sentence for each shortlisted car: “I prefer this because…” If the answer is only a payment, return to the itemized total. If the answer is a feature, confirm it is included on the car in the offer. Use the <a href="/tools/test-drive-checklist/">test-drive checklist</a> for the questions a quote cannot answer.</p>
        <h2>Official consumer resources</h2><ul class="source-list"><li><a href="https://www.canada.ca/en/financial-consumer-agency/services/loans/financing-car/shop-around.html">Financial Consumer Agency of Canada: compare auto-financing</a></li><li><a href="https://www.consumerfinance.gov/ask-cfpb/how-do-i-compare-auto-loan-offers-what-should-i-look-at-besides-the-monthly-payment-en-753/">U.S. Consumer Financial Protection Bureau: compare auto-loan offers</a></li></ul><p>Resources checked October 2, 2026.</p><p class="market-note">This is a comparison method, not legal or personalized financial advice. For local requirements, consult your province’s or state’s official consumer authority and the written contract. <a href="/comparisons/corolla-cross-vs-rav4/">See the Toyota SUV example</a>.</p>`)
    },
    {route:'/guides/cabin-tech-test-drive/',title:'Cabin technology test-drive checklist: phones, cameras & controls',description:'Test phone pairing, climate controls, reversing cameras and passenger practicality during a vehicle visit, then compare your notes.',written,
      body:wrap(pageIntro('BUYING GUIDE / DAILY USE','Try the tech before you buy the car.','Bring your phone, set the seat and repeat the same tasks in each vehicle.',[['Buying guides','/guides/'],['Cabin technology checklist',null]]),`
        <p class="updated">By <a href="/about/">Rishi · AutoTech Review</a> · October 2, 2026</p>
        <p>A touchscreen size or equipment list does not tell you whether a cabin works for you. Give each shortlisted vehicle the same ten-minute check while parked. Ask the retailer before pairing devices or changing profiles.</p>
        <h2>1. Connect your own phone</h2><p>Try the connection method offered by the exact trim: wired or wireless Apple CarPlay or Android Auto. Open your preferred navigation app, try audio playback and check where the phone and cable sit. Ask which services require a subscription after a trial and what remains available without one.</p>
        <h2>2. Find the controls you need most</h2><p>Adjust the temperature, fan, demister, volume and seat heating while parked. Check whether an on-screen menu hides a setting you use often. Set the driving position, then confirm you can read the instruments without moving your head around the steering wheel.</p>
        <h2>3. Check the parking view</h2><p>With the retailer’s help, inspect the reversing display and any available surround view. Confirm which cameras and parking sensors are actually fitted, how you activate them and whether the image is clear from your seated position. Ask how to clean exposed camera lenses.</p>
        <h2>4. Sit behind your own driving position</h2><p>Leave the driver’s seat where you need it, then sit in the rear. Check the doorway, foot room, headroom, rear vents and charging ports. Take the everyday luggage you expect to carry. If child-seat fit matters, arrange a hands-on check with your own seat and the vehicle manual.</p>
        <h2>5. Ask winter questions before winter arrives</h2><p>Confirm the exact trim’s heated-seat, heated-wheel and remote-start equipment. Ask about subscription requirements and operation with gloves. Locate the demister controls and ask about the correct tire specification and winter wheel options. A warm-weather visit cannot establish cold-weather range, heating speed or snow performance.</p>
        <h2>Save a useful comparison</h2><p>Write what worked, what needed help and what you still need to verify. The <a href="/tools/test-drive-checklist/">printable test-drive checklist</a> includes space for notes. Keep one copy per vehicle, then revisit the <a href="/shorts/">cabin detail Shorts</a> and <a href="/long-videos/">full videos</a> with those questions in mind.</p>
        <p>Before returning a demonstration car, remove your paired phone and personal navigation destinations with the retailer’s help. Check the owner’s manual for the procedure on that vehicle.</p>`)
    },
    {route:'/follow/',title:'Follow AutoTech Review: new videos, Shorts & RSS',description:'Follow AutoTech Review on YouTube, Instagram and TikTok, or add the latest-video RSS feed to your reader for new car coverage.',written,
      body:pageIntro('STAY IN THE LOOP','A new car question. A new reason to watch.','Choose how you want to keep up with AutoTech Review.')+`<section class="shell follow-layout"><article class="follow-feature"><span class="kicker">THE FULL CHANNEL</span><h2>Reviews when you have time.<br>Shorts when you have a minute.</h2><p>Subscribe on YouTube and choose notifications there. The website connects each upload with its vehicle, related coverage and buying tools.</p><a class="button" href="https://www.youtube.com/@autotechreview51" target="_blank" rel="noopener noreferrer">Visit the YouTube channel</a><div class="actions"><a class="text-link" href="/long-videos/">Browse Long Videos</a><a class="text-link" href="/shorts/">Browse Shorts</a></div></article><article class="follow-rss"><span class="kicker">YOUR READING LIST</span><h2>New uploads in your feed reader.</h2><p>Add this RSS address to your preferred reader. New video pages appear in the feed when the catalogue refreshes. No website account or email signup is needed.</p><a class="feed-address" href="/feed.xml">https://www.autotechreview.ca/feed.xml</a><button type="button" class="button secondary" data-copy-feed hidden>Copy RSS address</button><p data-feed-copy-status role="status"></p><p><a href="/long-videos-feed.xml">Long Videos RSS</a> · <a href="/shorts-feed.xml">Shorts RSS</a></p></article><article><span class="kicker">AROUND THE CHANNEL</span><h2>More quick looks.</h2><p><a class="text-link" href="https://www.instagram.com/auto.techreview/" target="_blank" rel="noopener noreferrer">Instagram · auto.techreview</a></p><p><a class="text-link" href="https://www.tiktok.com/@autotech.review" target="_blank" rel="noopener noreferrer">TikTok · autotech.review</a></p></article><article><span class="kicker">SEND A USEFUL LINK</span><h2>Help someone with their shortlist.</h2><p>Share a specific video, comparison or calculator result. The guides and video pages include a share button; copying a link also works.</p><button type="button" class="button secondary" data-share hidden>Share AutoTech Review</button><p data-share-status role="status"></p><a class="text-link" href="/media-kit/">Media and partnership information</a></article></section><section class="shell section">${guideCards}</section>`
    }
  ];
}
